# remap prefix from ctrl-b to ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on

set -g extended-keys on
set -g extended-keys-format csi-u

# start numbering at 1 to make more sense with keyboard layout
set -g base-index 1
setw -g pane-base-index 2

# vi keys for scrolling
setw -g mode-keys vi

# don't rename windows automatically
set-option -g allow-rename off

# easy config reloads
bind r source-file ~/.config/tmux/tmux.conf \; display-message "[tmux config reloaded]"

# system clipboard
set -g set-clipboard on

# intuitive split panes
bind | split-window -h
bind - split-window -h
unbind '"'
unbind %

# switch panes with alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# begone bells
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# visual styles
source-file ~/.config/tmux/styles.conf

